const express = require("express");
const router = express.Router();

const employees = [
    {
        id: "EMP001",
        name: "Ravi Kumar",
        image: "/assets/p1.jpg", // just the URL path
        email: "rk@gmail.com",
        phone: "+91-9876543210",
        designation: "Frontend Developer",
        department: "Engineering",
        projectId: "PRJ001",
        project: "CRM Redesign",
        status: "Active",
        joiningDate: "2022-04-15",
    },
    {
        id: "EMP002",
        name: "Anjali Mehta",
        image: "/assets/p2.jpg",
        email: "am@gmail.com",
        phone: "+91-9876501234",
        designation: "Backend Developer",
        department: "Engineering",
        projectId: "PRJ005",
        project: "Recruitment System",
        status: "Active",
        joiningDate: "2021-12-01",
    },
    {
        id: "EMP003",
        name: "Soham Roy",
        image: "/assets/p3.jpg",
        email: "soham.roy@gmail.com",
        phone: "+91-9876532198",
        designation: "UI/UX Designer",
        department: "Design",
        projectId: "PRJ001",
        project: "CRM Redesign",
        status: "Active",
        joiningDate: "2023-01-10",
    },
    {
        id: "EMP004",
        name: "Nikita Sharma",
        image: "/assets/p4.jpg",
        email: "nikita.sharma@gmail.com",
        phone: "+91-9867543210",
        designation: "QA Engineer",
        department: "Quality Assurance",
        projectId: "PRJ007",
        project: "E-Commerce Platform",
        status: "Active",
        joiningDate: "2022-07-22",
    },
    {
        id: "EMP005",
        name: "Arjun Verma",
        image: "/assets/p5.jpg",
        email: "arjun.verma@gmail.com",
        phone: "+91-9845671234",
        designation: "DevOps Engineer",
        department: "Infrastructure",
        projectId: "PRJ003",
        project: "Payment Gateway",
        status: "Inactive",
        joiningDate: "2020-09-01",
    },
    {
        id: "EMP006",
        name: "Priya Desai",
        image: "/assets/p6.jpg",
        email: "priya.desai@gmail.com",
        phone: "+91-9898989898",
        designation: "Product Manager",
        department: "Product",
        projectId: "PRJ009",
        project: "Learning Portal",
        status: "Active",
        joiningDate: "2021-05-15",
    },
    {
        id: "EMP007",
        name: "Manav Singh",
        image: "/assets/p7.jpg",
        email: "manav.singh@gmail.com",
        phone: "+91-9876123456",
        designation: "Mobile Developer",
        department: "Engineering",
        projectId: "PRJ004",
        project: "Delivery App",
        status: "On Leave",
        joiningDate: "2022-10-20",
    },
    {
        id: "EMP008",
        name: "Kavya Iyer",
        image: "/assets/p8.jpg",
        email: "kavya.iyer@gmail.com",
        phone: "+91-9765432109",
        designation: "HR Executive",
        department: "Human Resources",
        projectId: "PRJ010",
        project: "Onboarding System",
        status: "Active",
        joiningDate: "2023-02-01",
    }
];

// GET all employees
router.get("/", (req, res) => {
    res.json(employees);
});

module.exports = router;
